version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}   
      MYSQL_DATABASE: ${DATABASE}   
      MYSQL_USER: ${USERDB}            
      MYSQL_PASSWORD: ${PASSDB}           
    ports:
      - ${DB_PORT}:27017                     
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dbs

volumes:
  mysql-data:

networks:
  dbs:
    driver: bridge